### ISSUE TITLE
News Features

### ISSUE THREAD

**Issue by frankwiles** [cppalliance/temp-site#253] opened 2023-05-03 15:52 UTC
Users will add News in Django models 

## News Types 

- Video
- Blog post
- Link
- Polls  (future)
- Surveys (future)

The item is associated to the Django User who submitted it (so we can show the avatar) 

Show posted date

Ability to filter by category

Ability for users to post 

Moderation queue and require a moderator to approve before it goes live

**Comment by williln** [comment] 2023-06-27 21:01
Duplicate of #273 and related work

**Closed by williln** 2023-06-27 21:01 UTC
Labels: Feature, go-live, Backend
