### ISSUE TITLE
Libraries nonfunctional buttons

### ISSUE THREAD

**Issue by miguelportilla** [cppalliance/temp-site#406] opened 2023-05-31 16:41 UTC
![image](https://github.com/cppalliance/temp-site/assets/1524671/1f97f8e2-65b1-4129-9208-87e61a45b086)

The Libraries list, grid, and GitHub buttons are non-functional.

**Comment by gregnewman** [comment] 2023-06-01 23:20
This was a duplicate of another issue that's been closed so closing this one.

**Closed by gregnewman** 2023-06-01 23:20 UTC
Labels: HTML/CSS
