### ISSUE TITLE
Find out why ublas (and other) libraries downloaded twice, and keep it from happening again. 

### ISSUE THREAD

**Issue by dmenendez-gruposantander** [cppalliance/temp-site#317] opened 2023-05-11 15:09 UTC
https://www.boost.revsys.dev/libraries/ublas/ shows 500 - Server Error

Not sure if it is expected in the beta, or if it should show something?

**Comment by vinniefalco** [comment] 2023-05-11 15:11
Since https://github.,com/boostorg/ublas exists then it should show, not give an error.

**Comment by williln** [comment] 2023-05-26 17:22
@dmenendez-gruposantander @vinniefalco This is fixed. Somehow, two copies of the library were downloaded into the database. This created a collision in the `slug` field in the URL. It happened with a couple of other libraries; I manually deleted the duplicates and things are working now. 

I'm going to leave this issue open and rename it, so I can investigate why it happened.  

## notes to self 

- Downloaded as `ublas` and `uBLAS`. 
- Also saw it with `odeint` and `numeric/odeint` -- the `numeric/` makes me wonder if this has something to do with sub-modules? 
- I think it also happened with `interval` but I lost the third tab. It happened with three libraries. 
- Check the `.gitmodules` and `.libraries.json` of the affected libraries to see if something is funny there.

**Comment by williln** [comment] 2023-07-06 00:03
Can't reproduce any longer so closing as fixed but will re-open if needed.

**Closed by williln** 2023-07-06 00:03 UTC
Labels: Bug, Backend
